apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:  # We dont need to worry about converting to base64
  PGUSER: postgres
  PGHOST: fullstack-postgres
  PGDATABASE: dab
  PGPASSWORD: password